ffda-gluon-ssh-manager: add package
freifunk-gluon/community-packages pull request #24
Opened 2022-10-30 23:33 UTC by blocktrron

This adds the ffda-gluon-ssh-manager package.

This is a utility package which allows communities to add their own key-groups using their custom package to `/lib/gluon/ssh-manager/groups/<groupname>`.

Configuration is done using UCI. The following config-keys exist:

 - `gluon-ssh-manager.settings.enabled`
   - Default: 0
   - Enables gluon-ssh-manager.
 - `gluon-ssh-manager.settings.group`
   - Default: nil
   - Selects the key-group to roll out on a node.

Additional keys to be included independently of the selected group can be added to `/lib/gluon/ssh-manager/authorized_keys`.

To use ssh-manager functionality, the package needs to be enabled as well as a group being configured. If both requirements are met, gluon-ssh-manager will overwrite the system authorized_keys with the groups SSH keys as well as additionally defined SSH keys.

2022-10-31 06:21 UTC, herbetom commented
How is the management of `/lib/gluon/ssh-manager/groups/<groupname>` supposed to be done?

2022-10-31 08:31 UTC, AiyionPrime commented
A readme with a configuration example would be nice.

2022-10-31 09:01 UTC, AiyionPrime requested changes
I do like the idea of the package. Having different sets of keys will be a nice feature.

I do not like the adding character of this though.
Whenever a defined group grows or a new group gets added, it overwrites the file is overwritten. Having keys added though the configmode ui would not work like this anymore, would it?

2022-10-31 11:20 UTC, blocktrron commented on ffda-gluon-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-gluon-ssh-manager
> +if not file_exists(group_key_path) then
This would return true if the path is a directory, not a file.

2022-10-31 11:21 UTC, blocktrron commented on ffda-gluon-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-gluon-ssh-manager
> +-- Overwrite existing content
There is `/lib/gluon/ssh-manager/authorized_keys` for this case.

2022-11-01 12:17 UTC, AiyionPrime commented on ffda-gluon-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-gluon-ssh-manager
> +-- Overwrite existing content
your changes reflect what I intended, thanks!

2023-01-19 03:25 UTC, mkg20001 commented on ffda-gluon-ssh-manager/luasrc/lib/gluon/upgrade/860-ffda-gluon-ssh-manager
> +if not enabled then
removing the keys after being disabled sounds like something that should be done. the condition could be the presence of the block begin tag.

2023-06-13 21:19 UTC, mkg20001 commented
@blocktrron Can you update and merge this? Review is no longer a hard-requirement, so feel free to merge it once you feel like it.

2024-02-05 14:54 UTC, merged